1	DROP TABLE IF EXISTS `rec_act_log`;
1	CREATE TABLE `rec_act_log` (`act_id` int(10) unsigned NOT NULL AUTO_INCREMENT,`log_text` text,`rec_id` int(11) NOT NULL,`time` datetime NOT NULL,PRIMARY KEY (`act_id`)) ENGINE=MyISAM AUTO_INCREMENT=45912 DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `rec_wnd`;
1	CREATE TABLE `rec_wnd` (`wnd_id` int(11) NOT NULL AUTO_INCREMENT,`create_time` datetime NOT NULL,`rec_id` int(11) NOT NULL,`init_title` varchar(1000) CHARACTER SET gb2312 NOT NULL,`destory_time` datetime DEFAULT NULL,`classname` varchar(500) DEFAULT NULL,PRIMARY KEY (`wnd_id`),KEY `destory_time` (`destory_time`),KEY `rec_id` (`rec_id`)) ENGINE=MyISAM AUTO_INCREMENT=16026 DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `update_time`;
1	CREATE TABLE `update_time` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`version` int(10) unsigned NOT NULL,`time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `wnd_act_time`;
1	CREATE TABLE `wnd_act_time` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`wnd_id` int(10) unsigned NOT NULL,`last_time` int(10) unsigned NOT NULL,`focus` tinyint(1) NOT NULL,`focus_balance` double(15,3) unsigned NOT NULL,`last_time2` int(10) unsigned DEFAULT NULL,`avg_key` double(15,3) unsigned DEFAULT NULL,`avg_mouse` double(15,3) unsigned DEFAULT NULL,PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=79789 DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `wnd_keytype`;
1	CREATE TABLE `wnd_keytype` (`keytype_id` int(11) NOT NULL AUTO_INCREMENT,`wnd_id` int(11) NOT NULL,`keytype_count` int(11) NOT NULL,`time` datetime NOT NULL,PRIMARY KEY (`keytype_id`)) ENGINE=MyISAM AUTO_INCREMENT=44282 DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `wnd_lasttime_distribute`;
1	CREATE TABLE `wnd_lasttime_distribute` (`id` int(11) NOT NULL AUTO_INCREMENT,`start_point` int(10) unsigned NOT NULL,`end_point` int(10) unsigned NOT NULL,`count` int(10) unsigned NOT NULL,`distribution` double(11,8) unsigned NOT NULL,`add_distribution` double(11,8) unsigned NOT NULL,PRIMARY KEY (`id`)) ENGINE=MyISAM AUTO_INCREMENT=7816 DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `wnd_local`;
1	CREATE TABLE `wnd_local` (`local_id` int(11) NOT NULL AUTO_INCREMENT,`wnd_id` int(11) NOT NULL,`local_time` datetime NOT NULL,`x` int(11) NOT NULL,`y` int(11) NOT NULL,`cx` int(11) NOT NULL,`cy` int(11) NOT NULL,PRIMARY KEY (`local_id`)) ENGINE=MyISAM AUTO_INCREMENT=45313 DEFAULT CHARSET=gbk AVG_ROW_LENGTH=84;
1	DROP TABLE IF EXISTS `wnd_mouseclick`;
1	CREATE TABLE `wnd_mouseclick` (`mouse_id` int(11) NOT NULL AUTO_INCREMENT,`wnd_id` int(11) NOT NULL,`mouse_count` int(11) NOT NULL,`time` datetime NOT NULL,PRIMARY KEY (`mouse_id`)) ENGINE=MyISAM AUTO_INCREMENT=172580 DEFAULT CHARSET=gbk AVG_ROW_LENGTH=58;
1	DROP TABLE IF EXISTS `wnd_title`;
1	CREATE TABLE `wnd_title` (`title_id` int(11) NOT NULL AUTO_INCREMENT,`wnd_id` int(10) unsigned NOT NULL,`title` varchar(1000) CHARACTER SET utf8 NOT NULL,`time` datetime NOT NULL,PRIMARY KEY (`title_id`)) ENGINE=MyISAM AUTO_INCREMENT=23380 DEFAULT CHARSET=gbk;
1	DROP TABLE IF EXISTS `update_record`;
1	CREATE TABLE `update_record` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`version` int(10) unsigned NOT NULL,`time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',PRIMARY KEY (`id`)) ENGINE=MyISAM DEFAULT CHARSET=gbk;

